languageCode = "en"
languageName = "English"
displayName = "EN"
isoCode = "en"
weight = 1
rtl = false

title = " "
logo = "img/logo.webp"
description = "A powerful, lightweight theme for Hugo built with Tailwind CSS."
# copyright = "Copy, _right?_ :thinking_face:"

dateFormat = "2 January 2006"

[author]
  name = "Kyle Malloy, PE"
  image = "img/headshot.webp"
  headline = "Civil Engineer" 
  bio = "Civil Engineer"
  links = [
    { email = "mailto:kmalloy24@gmail.com" },
    { linkedin = "https://linkedin.com/in/malloykyle" },
    { twitter = "https://twitter.com/kylemalloype" },
    { mastodon = "https://mastodon.social/@kylemalloy" },
    { github = "https://github.com/kmalloy24" },
  ]
