languageCode = "en"
languageName = "English"
displayName = "EN"
isoCode = "en"
weight = 1
rtl = false

title = ""
logo = "img/logo.webp"
description = "Kyle Malloy, PE"
copyright = "© 2023 Kyle Malloy"

dateFormat = "2 January 2006"

[author]
  name = "Kyle Malloy, PE"
  image = "img/avatar.webp"
  headline = "Civil Engineer" 
  bio = "Civil Engineer"
  links = [
    { email = "mailto:kyle@malloy.dev" },
    { linkedin = "https://linkedin.com/in/malloykyle" },
    # { twitter = "https://twitter.com/kylemalloype" },
    # { mastodon = "https://mastodon.social/@kylemalloy" },
    # { github = "https://github.com/kmalloy24" },
  ]
